# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V2JmvLz81U76c-9-SvndiHZwVZEUd53e
"""

#!pip install streamlit pyngrok git+https://github.com/openai/whisper.git transformers sentence-transformers --quiet
#!apt-get install -y ffmpeg

import streamlit as st
import tempfile
import os

from summarizer import run_summarizer   # make sure summarizer.py is also uploaded to Colab

st.set_page_config(page_title="ClipMind – Video Summarizer")

st.title("🎬 ClipMind — The Intelligent Video Shrinker")
st.write("Upload a video and get an automatically generated highlight version ✨")

# Upload section
uploaded_video = st.file_uploader("Upload a video file", type=["mp4", "avi", "mkv"])

language = st.selectbox(
    "Select summary language",
    ["original", "english"]
)

if uploaded_video is not None:
    # Preview uploaded video
    st.subheader("Original video preview")
    st.video(uploaded_video)

    if st.button("🚀 Generate Highlight Summary"):
        with st.spinner("⏳ Processing video… This may take some time…"):

            # save uploaded video to temporary location
            temp_dir = tempfile.mkdtemp()
            input_path = os.path.join(temp_dir, uploaded_video.name)

            with open(input_path, "wb") as f:
                f.write(uploaded_video.read())

            # run your summarizer function
            output_path = run_summarizer(input_path, language=language)

        st.success("🎉 Summary video generated!")

        st.subheader("✨ Highlight Summary Video")
        st.video(output_path)